language: java
jdk:
  - openjdk11
dist: xenial
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: auth-chatapp
before_install: ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -e
