version: '3.8'

services:
  auth-chatapp-app:
    build: .
    restart: on-failure
    ports:
      - 8080:8081
    volumes:
      - .m2/root/.m2
    stdin_open: true
    tty: true
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      interval: 400s
      timeout: 5s
      retries: 5
      start_period: 400s